#!/usr/bin/env node
// Deterministic pre-LLM checks. Every failure is a finding with
// `source: "check"`; CRITICAL ones block the PR and can never be accepted via
// accepted.json. Writes .claude/pr-self-review/checks.json (keyed by the diff
// hash) for verdict.mjs.
//
//   node .claude/skills/pr-self-review/scripts/checks.mjs            # all checks
//   node .claude/skills/pr-self-review/scripts/checks.mjs --static   # skip typecheck/tests (tests of this script only)

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { collectDiffState, matchesAny, stateDir } from './diff-state.mjs';

const CRITICAL = 'CRITICAL';
const WARNING = 'WARNING';

function finding(check, severity, file, line, rule, evidence, fix) {
  return { source: 'check', skill: 'checks', check, severity, file, line, rule, evidence, fix };
}

const isNew = (f) => f.status === 'A';
const exists = (f) => f.status !== 'D';

// ---------------------------------------------------------------- migrations

const SCHEMA_GLOBS = ['server/src/db/schema.ts', 'server/src/db/schema/**'];
const MIGRATION_SQL = 'server/src/db/migrations/*.sql';
const MIGRATION_ANY = 'server/src/db/migrations/**';
const JOURNAL = 'server/src/db/migrations/meta/_journal.json';
// drizzle-kit's random names are `<adjective>_<noun>`; descriptive names we
// pass via `--name=` start with a verb.
const DESCRIPTIVE_MIGRATION = /^\d{4}_(add|drop|create|remove|rename|alter|backfill|init|update|change|make|set|index|fix|move|split|merge|extend|replace|seed|enable|disable|allow|restore|convert|normalize|link|unlink|introduce|delete|widen|narrow)_/;

export function checkMigrations(files) {
  const out = [];
  const schemaChanged = files.filter((f) => matchesAny(f.path, SCHEMA_GLOBS));
  const newSql = files.filter((f) => isNew(f) && matchesAny(f.path, [MIGRATION_SQL]));

  if (schemaChanged.length && !newSql.length) {
    out.push(finding('migration-drift', CRITICAL, schemaChanged[0].path, null,
      'schema changed without a migration',
      `changed: ${schemaChanged.map((f) => f.path).join(', ')}; no new ${MIGRATION_SQL}`,
      'cd server && pnpm db:generate --name=<what_changed>'));
  }

  for (const f of files) {
    if (!matchesAny(f.path, [MIGRATION_ANY]) || f.path === JOURNAL || isNew(f)) continue;
    // renamed/modified/deleted existing migration or snapshot
    out.push(finding('migration-hand-edit', CRITICAL, f.path, null,
      'existing migration modified',
      `status ${f.status}${f.oldPath ? ` (from ${f.oldPath})` : ''} — migrations are generated by drizzle-kit and never hand-edited`,
      'revert the file and generate a new migration with pnpm db:generate --name=...'));
  }

  for (const f of newSql) {
    const name = basename(f.path);
    if (!DESCRIPTIVE_MIGRATION.test(name)) {
      out.push(finding('migration-name', WARNING, f.path, null,
        'migration has a generated codename',
        `${name} does not start with a verb (add_/drop_/rename_/…)`,
        'delete the migration + its snapshot and regenerate with pnpm db:generate --name=<descriptive_name>'));
    }
  }
  return out;
}

// ---------------------------------------------------------------- shared mirror

const SERVER_CONTRACTS = 'server/src/vendor/shared/contracts/';
const CLIENT_CONTRACTS = 'client/src/vendor/shared/contracts/';

const normalize = (s) => s.replace(/\r\n/g, '\n');

export function checkSharedMirror(root, files) {
  const touched = files.filter((f) => f.path.startsWith(SERVER_CONTRACTS) || f.path.startsWith(CLIENT_CONTRACTS));
  if (!touched.length) return [];
  const names = new Set(touched.map((f) => f.path.split('/').pop()));
  const out = [];
  for (const name of names) {
    const s = join(root, SERVER_CONTRACTS, name);
    const c = join(root, CLIENT_CONTRACTS, name);
    const sOk = existsSync(s);
    const cOk = existsSync(c);
    if (!sOk && !cOk) continue;
    if (sOk !== cOk) {
      out.push(finding('shared-mirror', CRITICAL, (sOk ? SERVER_CONTRACTS : CLIENT_CONTRACTS) + name, null,
        'contract not mirrored',
        `${name} exists only under ${sOk ? 'server' : 'client'}/src/vendor/shared/contracts`,
        'server/src/vendor/shared is the source — copy the file to client/src/vendor/shared/contracts (or delete both)'));
    } else if (normalize(readFileSync(s, 'utf8')) !== normalize(readFileSync(c, 'utf8'))) {
      out.push(finding('shared-mirror', CRITICAL, CLIENT_CONTRACTS + name, null,
        'contract mirror drifted',
        `${SERVER_CONTRACTS}${name} and ${CLIENT_CONTRACTS}${name} differ`,
        'edit server/src/vendor/shared (the source) and copy it over the client mirror'));
    }
  }
  return out;
}

// ---------------------------------------------------------------- lock files

const LOCKFILES = {
  server: 'server/pnpm-lock.yaml',
  client: 'client/pnpm-lock.yaml',
  'reviewer-core': 'reviewer-core/package-lock.json',
  e2e: 'e2e/package-lock.json',
};

export function checkLockfiles(files) {
  const paths = new Set(files.map((f) => f.path));
  const out = [];
  for (const [pkg, lock] of Object.entries(LOCKFILES)) {
    if (paths.has(lock) && !paths.has(`${pkg}/package.json`)) {
      out.push(finding('lockfile', CRITICAL, lock, null,
        'lock file changed without package.json',
        `${lock} changed but ${pkg}/package.json did not`,
        `revert ${lock}, or make the dependency change in ${pkg}/package.json and regenerate the lock via the package manager`));
    }
  }
  return out;
}

// ---------------------------------------------------------------- secrets

export const SECRET_PATTERNS = [
  ['OpenAI/Anthropic key', /(?<![A-Za-z0-9])sk-(?:ant-|proj-)?[A-Za-z0-9_-]{20,}/],
  ['GitHub token', /(?<![A-Za-z0-9])gh[pousr]_[A-Za-z0-9]{36,}/],
  ['GitHub fine-grained token', /(?<![A-Za-z0-9])github_pat_[A-Za-z0-9_]{22,}/],
  ['AWS access key', /(?<![A-Z0-9])AKIA[0-9A-Z]{16}(?![A-Z0-9])/],
  ['private key', /-----BEGIN [A-Z ]*PRIVATE KEY-----/],
];

const redact = (s) => (s.length <= 8 ? '***' : `${s.slice(0, 6)}…(${s.length} chars)`);

export function checkSecrets(files, added) {
  const out = [];
  for (const f of files) {
    const name = basename(f.path);
    if (exists(f) && /^\.env(\..+)?$/.test(name) && name !== '.env.example') {
      out.push(finding('secrets', CRITICAL, f.path, null, 'env file in the diff',
        `${f.path} is part of the change set`,
        'remove it from git (git rm --cached) — secrets live in ~/.devdigest/secrets.json'));
    }
    if (matchesAny(f.path, ['**/pnpm-lock.yaml', '**/package-lock.json'])) continue;
    for (const { line, text } of added.get(f.path) ?? []) {
      for (const [label, re] of SECRET_PATTERNS) {
        const m = re.exec(text);
        if (m) {
          out.push(finding('secrets', CRITICAL, f.path, line, `hardcoded ${label}`,
            `matched ${redact(m[0])}`,
            'remove the value, rotate the credential, and read it from ~/.devdigest/secrets.json / Settings instead'));
        }
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------- missing tests

const NEEDS_TEST = [
  'server/src/**/service.ts',
  'server/src/**/repository.ts',
  'server/src/**/routes.ts',
  'client/src/**/*.tsx',
];
const NO_TEST_NEEDED = [
  '**/*.test.tsx',
  'client/src/vendor/**',
  'client/src/app/**/{page,layout,template,default,loading,error,global-error,not-found}.tsx',
];

// Test placement is per package (root AGENTS.md): client colocates
// `<Subject>.test.ts(x)`; server and reviewer-core keep tests in a sibling
// `test/` folder named after the module (`server/test/pulls-status.test.ts`).
const TEST_DIR_PACKAGES = /^(server|reviewer-core)\//;

/** Where a test for `path` would live, and whether one exists. */
export function findTest(root, path) {
  const pkg = TEST_DIR_PACKAGES.exec(path)?.[1];
  if (pkg) {
    const subject = /\/modules\/([^/]+)\//.exec(path)?.[1] ?? basename(path).replace(/\.tsx?$/, '');
    const dir = join(root, pkg, 'test');
    const found = existsSync(dir) && readdirSync(dir).some((n) => n.startsWith(subject) && /\.test\.ts$/.test(n));
    return { found, expected: `${pkg}/test/${subject}*.test.ts` };
  }
  const stem = path.replace(/\.(tsx?)$/, '');
  const candidates = ['.test.ts', '.test.tsx'].map((ext) => stem + ext);
  return { found: candidates.some((c) => existsSync(join(root, c))), expected: `${basename(stem)}.test.ts(x) next to it` };
}

export function checkMissingTests(root, files) {
  const out = [];
  for (const f of files) {
    if (!isNew(f) || !matchesAny(f.path, NEEDS_TEST) || matchesAny(f.path, NO_TEST_NEEDED)) continue;
    const { found, expected } = findTest(root, f.path);
    if (!found) {
      out.push(finding('missing-test', WARNING, f.path, null, 'new module without a test',
        `no ${expected}`,
        `add ${expected} (test placement is per package — see root AGENTS.md)`));
    }
  }
  return out;
}

// ---------------------------------------------------------------- typecheck / tests

const HERMETIC_TESTS = new Set(['server', 'client', 'reviewer-core']);

const ANSI = /\x1b\[[0-9;]*[A-Za-z]/g;

export function tail(text, n = 40) {
  return text.replace(ANSI, '').split(/\r?\n/).filter((l) => l.trim()).slice(-n).join('\n');
}

function runNode(cwd, args) {
  const started = Date.now();
  const r = spawnSync(process.execPath, args, {
    cwd,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    timeout: 10 * 60 * 1000,
    env: { ...process.env, CI: '1', FORCE_COLOR: '0', NO_COLOR: '1' },
  });
  return { ok: r.status === 0, ms: Date.now() - started, output: `${r.stdout ?? ''}\n${r.stderr ?? ''}${r.error ? `\n${r.error.message}` : ''}` };
}

function tsconfigFor(pkgDir) {
  const script = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')).scripts?.typecheck ?? '';
  return /-p\s+(\S+)/.exec(script)?.[1] ?? 'tsconfig.json';
}

export function runToolchain(root, packages) {
  const findings = [];
  const ran = [];
  for (const pkg of packages) {
    const dir = join(root, pkg);
    const tsc = join(dir, 'node_modules/typescript/bin/tsc');
    if (!existsSync(tsc)) {
      findings.push(finding('toolchain', CRITICAL, `${pkg}/package.json`, null, 'dependencies not installed',
        `${pkg}/node_modules/typescript is missing — typecheck/tests cannot run, so the change cannot be verified`,
        `install dependencies in ${pkg}/ and re-run /pr-self-review`));
      continue;
    }
    const tc = runNode(dir, [tsc, '--noEmit', '-p', tsconfigFor(dir)]);
    ran.push({ check: 'typecheck', package: pkg, ok: tc.ok, ms: tc.ms });
    if (!tc.ok) {
      findings.push(finding('typecheck', CRITICAL, `${pkg}/`, null, `typecheck fails in ${pkg}`, tail(tc.output), `fix the type errors (cd ${pkg} && pnpm typecheck)`));
    }

    if (!HERMETIC_TESTS.has(pkg)) continue;
    const vitest = join(dir, 'node_modules/vitest/vitest.mjs');
    const args = [vitest, 'run'];
    if (pkg === 'server') args.push('--exclude', '**/*.it.test.ts');
    const t = runNode(dir, args);
    ran.push({ check: 'tests', package: pkg, ok: t.ok, ms: t.ms });
    if (!t.ok) {
      findings.push(finding('tests', CRITICAL, `${pkg}/`, null, `hermetic tests fail in ${pkg}`, tail(t.output), `fix the failing tests (see ${pkg}/AGENTS.md for the exact test command)`));
    }
  }
  return { findings, ran };
}

// ---------------------------------------------------------------- orchestration

export function runStaticChecks(state) {
  const { root, files, added } = state;
  return [
    ...checkMigrations(files),
    ...checkSharedMirror(root, files),
    ...checkLockfiles(files),
    ...checkSecrets(files, added),
    ...checkMissingTests(root, files),
  ];
}

function isMain() {
  return process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
}

if (isMain()) {
  try {
    const state = collectDiffState();
    const staticOnly = process.argv.includes('--static');
    const findings = runStaticChecks(state);
    const ran = [{ check: 'static', ok: true }];
    if (!staticOnly) {
      const tc = runToolchain(state.root, state.packages);
      findings.push(...tc.findings);
      ran.push(...tc.ran);
    }
    const result = {
      hash: state.hash,
      complete: !staticOnly,
      ran,
      counts: {
        CRITICAL: findings.filter((f) => f.severity === CRITICAL).length,
        WARNING: findings.filter((f) => f.severity === WARNING).length,
      },
      findings,
      at: new Date().toISOString(),
    };
    const dir = stateDir(state.root);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'checks.json'), JSON.stringify(result, null, 2));
    process.stdout.write(JSON.stringify(result, null, 2) + '\n');
  } catch (err) {
    process.stderr.write(`checks: ${err.message}\n`);
    process.exit(2);
  }
}
