import type { CSSProperties } from "react";

/** Co-located styles for ConventionCard (mirrors SkillCard's visual language). */
export const s = {
  card: (accepted: boolean): CSSProperties => ({
    display: "flex",
    gap: 16,
    padding: 16,
    borderRadius: 8,
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${accepted ? "var(--ok)" : "var(--border-strong)"}`,
    background: "var(--bg-elevated)",
    marginBottom: 12,
  }),
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  ruleRow: { display: "flex", alignItems: "flex-start", gap: 10, marginBottom: 10 } satisfies CSSProperties,
  rule: {
    flex: 1,
    fontSize: 14,
    fontWeight: 600,
    fontStyle: "italic",
    lineHeight: 1.45,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  inlineCode: {
    fontStyle: "normal",
    fontSize: 12.5,
    padding: "1px 5px",
    borderRadius: 4,
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  evidence: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    overflow: "hidden",
    marginBottom: 10,
  } satisfies CSSProperties,
  evidenceHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    fontSize: 12,
    color: "var(--text-secondary)",
    background: "var(--bg-surface)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "10px 12px",
    fontSize: 12.5,
    lineHeight: 1.5,
    background: "var(--code-bg)",
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  noEvidence: { fontSize: 12, color: "var(--text-muted)", marginBottom: 10 } satisfies CSSProperties,
  confidenceRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  confidenceBar: { width: 90 } satisfies CSSProperties,
  actions: { display: "flex", flexDirection: "column", gap: 8, width: 120, flexShrink: 0 } satisfies CSSProperties,
  editor: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 10 } satisfies CSSProperties,
  editorActions: { display: "flex", gap: 8 } satisfies CSSProperties,
} as const;
